export const tableActions = {
  FETCH_DATA_SAGA: "FETCH_DATA_SAGA",
  GET_TABLE_DATA_SUCCESS: "GET_TABLE_DATA_SUCCESS",
  GET_TABLE_DATA_ERROR: "GET_TABLE_DATA_ERROR",
  ADD_ROW: "ADD_ROW",
  DELETE_SINGLE_ROW_DATA: "DELETE_SINGLE_ROW_DATA",
  DELETE_SINGLE_ROW_DATA_SUCCESS: "DELETE_SINGLE_ROW_DATA_SUCCESS",
  DELETE_SINGLE_ROW_DATA_ERROR: "DELETE_SINGLE_ROW_DATA_ERROR",
  UPDATE_SINGLE_ROW_DATA: "UPDATE_SINGLE_ROW_DATA",
  UPDATE_SINGLE_ROW_DATA_SUCCESS: "UPDATE_SINGLE_ROW_DATA_SUCCESS",
  UPDATE_SINGLE_ROW_DATA_ERROR: "UPDATE_SINGLE_ROW_DATA_ERROR",
  ADD_SINGLE_ROW_DATA: "ADD_SINGLE_ROW_DATA",
  ADD_SINGLE_ROW_DATA_SUCCESS: "ADD_SINGLE_ROW_DATA_SUCCESS",
  ADD_SINGLE_ROW_DATA_ERROR: "ADD_SINGLE_ROW_DATA_ERROR",
  SET_SELECTED_CELL_KEY: "SET_SELECTED_CELL_KEY"
};

export default tableActions;
